### PR TITLE
JC Connector

### PR DESCRIPTION
**Pull request by kellyjonbrazil**
I updated the connector name and added some more parser checks and debug info.

### CODE REVIEW

**Comment by kellyjonbrazil** [comment]
Is there a way to make the `parser` field a dynamic dropdown list based on a function? I would like to call `jc.standard_parser_mod_list()` and populate the dropdown list.

**Comment by kellyjonbrazil** [comment]
Is there a way to make the `parser` field a dynamic dropdown list based on a function? I would like to call `jc.standard_parser_mod_list()` and populate the options

**Comment by cs-pooja-singh** [comment]
yes, there is @kellyjonbrazil. Many of our connectors do that. check the vmware-vsphere connector for example. In the info jso, those action params have an 'apiOperation' key that maps to a function that can be called. I can walk you through in a call as needed

**Comment by kellyjonbrazil** [comment]
I was able to change the `JC Parser` field to a Select field via `apiOperation`. Much better!

**Review by cs-shravan-konthalapally — APPROVED** [review]

**Pull request merged**
